# Generated by Django 6.0.7 on 2026-08-14 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_branch'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0026_remove_optiongroup_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must start with +251 followed by 9 digits, e.g. +251 911 234 567', regex='^\\+251(?:\\s?\\d{3}\\s?\\d{3}\\s?\\d{3})$')]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='unique_phone_nonempty'),
        ),
    ]
