# Generated by Django 6.0.7 on 2026-09-02 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must start with +251 or 0 followed by 9-10 digits, e.g. +251 911 234 567 or 0911 234 567', regex='^(\\+251|0)(?:\\s?\\d{3}\\s?\\d{3}\\s?\\d{3,4})$')]),
        ),
    ]
