# Generated by Django 6.0.7 on 2026-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_systems/')),
                ('details', models.TextField(blank=True, help_text='Instructions shown to the customer, e.g. account number')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
