# Generated by Django 6.0.7 on 2026-08-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_seed_payment_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='cashier_enabled',
            field=models.BooleanField(default=True, help_text='Available to cashiers'),
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='customer_enabled',
            field=models.BooleanField(default=True, help_text='Available to customers'),
        ),
    ]
