# Generated by Django 6.0.7 on 2026-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_proof_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_attempts',
            field=models.PositiveIntegerField(default=0, help_text='How many times the cashier has rejected this payment proof'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Payment Rejected')], default='PENDING', max_length=20),
        ),
    ]
