# Generated by Django 6.0.7 on 2026-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordernotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason provided by the cashier when rejecting payment proof'),
        ),
    ]
