# Generated by Django 6.0.7 on 2026-08-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='message_amharic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
