# Generated by Django 6.0.7 on 2026-08-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_notification_amharic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProofAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_proofs/')),
                ('attempt', models.PositiveIntegerField()),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_history', to='orders.order')),
            ],
            options={
                'ordering': ['attempt'],
            },
        ),
    ]
