# Generated by Django 6.0.7 on 2026-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_account',
            field=models.CharField(blank=True, default='', help_text='Account / phone number the customer received the refund on', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_method',
            field=models.CharField(blank=True, default='', help_text='Payment channel used to return the money (PaymentSystem code)', max_length=20),
        ),
    ]
