# Generated by Django 6.0.7 on 2026-08-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='for_refund',
            field=models.BooleanField(default=True, help_text='Can be selected by customers to receive refunds'),
        ),
    ]
