# Generated by Django 6.0.7 on 2026-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_restaurantinfo_latitude_restaurantinfo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_amharic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
