# Generated by Django 6.0.7 on 2026-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_name_amharic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_amharic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_amharic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
