# Generated by Django 6.0.7 on 2026-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description_amharic_product_name_amharic'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='name_amharic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
