# Generated by Django 6.0.7 on 2026-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_optiongroup_name_amharic'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
