# Generated by Django 6.0.7 on 2026-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_optiongroup_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvalue',
            name='name_amharic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
