# Generated by Django 6.0.7 on 2026-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sociallink'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sociallink',
            constraint=models.UniqueConstraint(fields=('restaurant', 'platform'), name='unique_social_platform_per_restaurant'),
        ),
    ]
