# Generated by Django 6.0.7 on 2026-08-05 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must start with +251 followed by 9 digits, e.g. +251 911 234 567', regex='^\\+251(?:\\s?\\d{3}\\s?\\d{3}\\s?\\d{3})$')]),
        ),
    ]
