# Generated by Django 6.0.7 on 2026-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='about_amharic',
            field=models.TextField(blank=True),
        ),
    ]
