# Generated by Django 6.0.7 on 2026-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_restaurantinfo_about_restaurantinfo_about_amharic'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
