# Generated by Django 6.0.7 on 2026-08-08 07:46

from django.db import migrations


def backfill_main_branches(apps, schema_editor):
    RestaurantInfo = apps.get_model("products", "RestaurantInfo")
    Branch = apps.get_model("products", "Branch")
    for restaurant in RestaurantInfo.objects.filter(branches__isnull=True):
        Branch.objects.create(
            restaurant=restaurant,
            name=restaurant.name or "Main Branch",
            is_main=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_branch_is_main'),
    ]

    operations = [
        migrations.RunPython(backfill_main_branches, migrations.RunPython.noop),
    ]
