# Generated by Django 6.0.7 on 2026-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_backfill_main_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='optiongroup',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
