# Generated by Django 6.0.7 on 2026-08-12 05:44

from django.db import migrations, models
from django.db.models import Count


def make_unique_names(apps, schema_editor):
    OptionGroup = apps.get_model("products", "OptionGroup")
    OptionValue = apps.get_model("products", "OptionValue")

    def rename_duplicates(model, qualifier_attr):
        for row in (
            model.objects.values("name")
            .annotate(count=Count("id"))
            .filter(count__gt=1)
        ):
            name = row["name"]
            dupes = list(model.objects.filter(name=name).order_by("id"))
            for obj in dupes[1:]:
                qualifier = obj
                for part in qualifier_attr.split("__"):
                    qualifier = getattr(qualifier, part)
                new_name = f"{name} ({qualifier})"
                base = new_name
                i = 2
                while model.objects.filter(name=new_name).exists():
                    new_name = f"{base} {i}"
                    i += 1
                obj.name = new_name
                obj.save(update_fields=["name"])

    rename_duplicates(OptionGroup, "product__name")
    rename_duplicates(OptionValue, "option_group__product__name")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_category_options_alter_optiongroup_options_and_more"),
    ]

    operations = [
        migrations.RunPython(make_unique_names, noop),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="optionvalue",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
