# Generated by Django 6.0.7 on 2026-08-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_category_name_alter_optiongroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'unique': 'A category with this name already exists.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='name',
            field=models.CharField(error_messages={'unique': 'An option group with this name already exists.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='name',
            field=models.CharField(error_messages={'unique': 'An option value with this name already exists.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={'unique': 'A product with this name already exists.'}, max_length=100, unique=True),
        ),
    ]
