# Generated by Django 6.0.7 on 2026-08-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_name_alter_optiongroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_product_name_per_category', violation_error_message='A product with this name already exists in this category.'),
        ),
    ]
