# Generated by Django 6.0.7 on 2026-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='optiongroup',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_option_group_name_per_product', violation_error_message='An option group with this name already exists for this product.'),
        ),
        migrations.AddConstraint(
            model_name='optionvalue',
            constraint=models.UniqueConstraint(fields=('option_group', 'name'), name='unique_option_value_name_per_group', violation_error_message='An option value with this name already exists in this group.'),
        ),
    ]
