# Generated by Django 6.0.7 on 2026-08-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_optiongroup_name_alter_optionvalue_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiongroup',
            name='price',
        ),
    ]
