# Generated by Django 6.0.7 on 2026-08-21 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_optiongroup_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must start with +251 or 0 followed by 9 digits, e.g. +251 911 234 567 or 0911 234 567', regex='^(\\+251|0)(?:\\s?\\d{3}\\s?\\d{3}\\s?\\d{3})$')]),
        ),
    ]
