# Generated by Django 6.0.7 on 2026-08-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_category_available_from_category_available_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
