# Generated by Django 6.0.7 on 2026-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_restaurantinfo_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='faqs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='faqs_amharic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='privacy_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='privacy_policy_amharic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='terms_amharic',
            field=models.TextField(blank=True),
        ),
    ]
