# Generated by Django 6.0.7 on 2026-08-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_restaurantinfo_faqs_restaurantinfo_faqs_amharic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=20),
        ),
    ]
