# Generated by Django 6.0.7 on 2026-09-01 04:52

from django.db import migrations, models


def backfill_category_type(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    Product = apps.get_model("products", "Product")
    for category in Category.objects.all():
        has_drink = Product.objects.filter(category=category, product_type="drink").exists()
        if has_drink:
            category.type = "drink"
            category.save(update_fields=["type"])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=20),
        ),
        migrations.RunPython(backfill_category_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
